name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  symfony-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql
          coverage: none
      - name: Install Composer dependencies
        working-directory: ./SAE/backend
        run: composer install --prefer-dist --no-progress

      - name: Check PHP syntax
        working-directory: ./SAE/backend
        run: find src/ -name "*.php" -exec php -l {} \;

      - name: Validate Doctrine schema
        working-directory: ./SAE/backend
        run: php bin/console doctrine:schema:validate --skip-sync
        